# Generated by Django 5.1.4 on 2024-12-17 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(help_text='поле индекса записи', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название альбома', max_length=50, verbose_name='Название')),
                ('relesased_at', models.DateField(help_text='Дата выпуска альбома', verbose_name='Дата выпуска')),
                ('tracks', models.IntegerField(help_text='Кол-во треков в альбоме', validators=[django.core.validators.MinValueValidator(1, 'Значение должно быть больше или равно %(limit_value)s.')], verbose_name='Кол-во треков')),
                ('artist', models.CharField(blank=True, help_text='Артист', max_length=50, verbose_name='Артист')),
                ('genre', models.CharField(blank=True, help_text='Жанр', max_length=50, verbose_name='Жанр')),
                ('type', models.CharField(blank=True, help_text='Тип альбома Дэмо / Дебютный / Промо / и т.д.', max_length=50, verbose_name='Тип альбома')),
            ],
        ),
    ]
